/* empty css                            */
import { e as createAstro, f as createComponent, r as renderTemplate, m as maybeRenderHead, g as addAttribute, j as renderComponent } from '../astro_1Ub4ig7k.mjs';
import { $ as $$Layout } from './embeded_nWbSBXDt.mjs';

const $$Astro$1 = createAstro();
const $$Field = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$Field;
  const { name, label, type, containerClass } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<div${addAttribute(`flex flex-col gap-2 flex-1${containerClass ? " " + containerClass : ""}`, "class")}> ${type === "checkbox" && renderTemplate`<label${addAttribute(name, "for")} class="text-white"> ${label} <input${addAttribute(name, "id")}${addAttribute(name, "name")}${addAttribute(type, "type")} class="py-2 px-4 rounded-lg"> </label>`} ${type !== "submit" && type !== "button" && type !== "checkbox" && renderTemplate`<label${addAttribute(name, "for")} class="text-white"> ${label} </label>`} ${type !== "submit" && type !== "button" && type !== "checkbox" && renderTemplate`<input${addAttribute(name, "id")}${addAttribute(name, "name")}${addAttribute(type, "type")} class="py-2 px-4 rounded-lg">`} ${(type === "submit" || type === "button") && renderTemplate`<buttom${addAttribute(name, "id")}${addAttribute(name, "name")}${addAttribute(type, "type")} class="py-2 px-8 text-center rounded-lg bg-amber-300 hover:bg-amber-400 active:bg-amber-500 cursor-pointer"> ${label} </buttom>`} </div>`;
}, "/mnt/nvme0n1p1/projetos/Astro/product-viewer-generator/src/components/Field.astro", void 0);

const $$Astro = createAstro();
const $$Index = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Index;
  return renderTemplate` ${renderComponent($$result, "Layout", $$Layout, { "title": "Welcome to Astro." }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<main class="w-full flex flex-col justify-center items-center p-5"> <h1 class="text-center text-2xl uppercase mb-14 text-woodsmoke-50">Product viewer generator</h1> <div class="w-full flex flex-col items-center mb-14"> <div class="p-8 bg-white w-full max-w-5xl"> <div class="p-5 border bg-woodsmoke-50 shadow-lg border-woodsmoke-200 rounded-[20px] flex items-center gap-4 relative z-10"> <div class="w-[200px] h-[200px] border border-woodsmoke-200 rounded-[20px] overflow-hidden p-2.5 bg-white"> <img src="https://placehold.co/200x200/edeef1/b4bac5/webp" alt="" id="example_product_image" class="w-full h-full rounded-[15px]"> </div> <div class="flex flex-1 flex-col gap-4 items-start justify-center"> <div class="bg-green-200 text-green-700 px-5 py-2 rounded-[10px]" id="example_product_tag">Etiqueta</div> <h2 class="text-2xl" id="example_product_name">Nome do produto</h2> <div> <img src="https://placehold.co/150x50/edeef1/b4bac5/webp?text=Logo+da+loja+150+x+50" alt="" id="example_product_store_logo" class="max-h-[50px]"> </div> </div> <div class="flex flex-col items-center"> <p class="text-center mb-5 text-2xl" id="example_product_price">R$ 1000,00</p> <a href="#" target="_blank" id="example_product_link" class="px-10 py-2 rounded-[10px] bg-green-600 hover:bg-green-700 active:bg-green-800 text-woodsmoke-50 text-xl">Ir para loja</a> </div> </div> <div class="px-5 pt-8 pb-1 rounded-b-[20px] -mt-7 bg-woodsmoke-50 text-woodsmoke-300 text-[9px] relative z-0">
Develope by: <a href="https://lucastiago.com.br" target="_blank" class="hover:text-amber-500">LTCODE</a> | Gostaria de ter um product viewer em seu site? <a href="#" target="_blank" class="hover:text-amber-500">Clique aqui</a>.
</div> </div> </div> <div class="mb-14"> <form class="flex flex-wrap max-w-3xl gap-4" id="form_generator"> ${renderComponent($$result2, "Field", $$Field, { "name": "product_name", "label": "Nome do produto:", "type": "text", "containerClass": "basis-full" })} <div> ${renderComponent($$result2, "Field", $$Field, { "name": "product_price", "label": "Pre\xE7o do prodito:", "type": "number" })} ${renderComponent($$result2, "Field", $$Field, { "name": "product_hidden_price", "label": "Ocultar pre\xE7o:", "type": "checkbox" })} </div> ${renderComponent($$result2, "Field", $$Field, { "name": "product_tag", "label": "Etiqueta:" })} ${renderComponent($$result2, "Field", $$Field, { "name": "product_store_logo", "label": "URL Logo da loja:" })} ${renderComponent($$result2, "Field", $$Field, { "name": "product_image", "label": "URL da image do prodito:", "type": "text", "containerClass": "basis-full" })} ${renderComponent($$result2, "Field", $$Field, { "name": "product_link", "label": "Link do produto:", "type": "text", "containerClass": "basis-full" })} ${renderComponent($$result2, "Field", $$Field, { "name": "product_button", "label": "Gerar c\xF3digo", "type": "submit", "containerClass": "basis-full mt-5" })} </form> <div class="fixed w-full h-full top-0 left-0 z-50 bg-woodsmoke-950 bg-opacity-50 flex justify-center items-center shadow-lg invisible" id="modal_code"> <div class="absolute w-full max-w-3xl h-full max-h-[568px] bg-woodsmoke-50 rounded-[20px]"> <div class="w-full bg-woodsmoke-200 rounded-t-[20px] p-4 border-b border-woodsmoke-300 flex justify-between mb-5"> <div>Código</div> <button id="button_close_modal_code">X</button> </div> <div class="p-5"> <textarea id="textarea_modal_code" class="w-full rounded-[20px] p-5 shadow-lg resize-none bg-white text-woodsmoke-600" rows="10" disabled>Código</textarea> </div> </div> </div> </div> </main> ` })}`;
}, "/mnt/nvme0n1p1/projetos/Astro/product-viewer-generator/src/pages/index.astro", void 0);

const $$file = "/mnt/nvme0n1p1/projetos/Astro/product-viewer-generator/src/pages/index.astro";
const $$url = "";

export { $$Index as default, $$file as file, $$url as url };
